name: Terraform CI/CD

on:
  pull_request:
    paths: ['**.tf', '**.tfvars']
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341514666:role/ci-cd
          aws-region: eu-central-1

      - name: Who am I (OIDC debug)
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd envs/dev
          terraform init -input=false

      - name: Terraform Format
        run: |
          cd envs/dev
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd envs/dev
          terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cd envs/dev
          terraform plan -no-color -input=false

      # üí¨ PR comment (–±–µ–∑ stdout ‚Äì –ø–æ-–±–µ–∑–æ–ø–∞—Å–Ω–æ)
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Terraform plan executed. Check Actions logs for full output."
            })

      # üöÄ APPLY ‚Äî —Å–∞–º–æ –ø—Ä–∏ merge –≤ master
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cd envs/dev
          terraform apply -auto-approve -input=false
