name: Terraform CI/CD

on:
  pull_request:
    paths: ['**.tf', '**.tfvars']
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341514666:role/ci-cd
          aws-region: eu-central-1

      - name: Who am I (OIDC debug)
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd envs/dev
          terraform init -input=false

      - name: Terraform Format
        run: |
          cd envs/dev
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd envs/dev
          terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'      
        run: |
          cd envs/dev
          terraform plan -input=false -out=tfplan
        continue-on-error: true


      - name: Terraform Show Plan
        id: show
        if: github.event_name == 'pull_request'
        run: |
          cd envs/dev
          terraform show -no-color tfplan > plan.txt

          echo "stdout<<EOF" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            ### Terraform Plan              
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${{ steps.show.outputs.stdout }}
            \`\`\`
            
            </details>
            `
                  });
            
      

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cd envs/dev
          terraform apply -auto-approve -input=false
